Update docker-compose config for MinIO server

diff --git a/central/docker-compose.yml b/central/docker-compose.yml
--- a/central/docker-compose.yml
+++ b/central/docker-compose.yml
@@ -67,17 +67,33 @@ services:
 
   minio:
     image: quay.io/minio/minio
-    # container_name: minio
     restart: always
+    entrypoint: /bin/sh   
     environment:
-      MINIO_ROOT_USER: minioadmin 
+      MINIO_ROOT_USER: minioadmin
       MINIO_ROOT_PASSWORD: minioadmin
     ports:
       - "9000:9000"
       - "9001:9001"
     volumes:
       - ./data/minio:/var/lib/minio
-    command: server /data --console-address ":9001"
+    command: -c "
+      minio server /data --console-address ':9001' &
+      pid=$!;
+      sleep 5;
+
+      echo '🔹 Setting up mc client...';
+      mc alias set local http://localhost:9000 minioadmin minioadmin;
+
+      if ! mc ls local/pos >/dev/null 2>&1; then
+        echo '🔹 Bucket pos not found. Creating...';
+        mc mb local/pos;
+      else
+        echo '✅ Bucket pos already exists. Skipping creation...';
+      fi;
+
+      wait $pid
+      "
 
   cassandra:
     image: cassandra:4.1
